"""Interfaces the pipelines depend on. Adapters implement them; tests use in-memory fakes."""

from collections.abc import Sequence
from typing import Protocol

from docqa.domain.models import Chunk, DocMetadata, ParsedDocument


class BlobStore(Protocol):
    def get(self, key: str) -> bytes: ...
    def put(self, key: str, data: bytes, content_type: str) -> None: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
    def list_keys(self, prefix: str) -> list[str]: ...


class VisionTranscriber(Protocol):
    def transcribe(self, image: bytes, image_format: str) -> str:
        """Return the page content as Markdown (tables as Markdown tables)."""
        ...


class MetadataExtractor(Protocol):
    def extract(self, text: str) -> DocMetadata: ...


class Embedder(Protocol):
    @property
    def dimensions(self) -> int: ...
    def embed(self, texts: Sequence[str]) -> list[list[float]]: ...


class ChunkIndex(Protocol):
    def upsert_document(
        self, doc: ParsedDocument, chunks: Sequence[Chunk], vectors: Sequence[Sequence[float]]
    ) -> None: ...
    def delete_document(self, doc_id: str) -> None: ...
    def count(self) -> int: ...
